server:
  port: 8081

api:
  base-url:
    txt2imgUrl: http://127.0.0.1:7861/sdapi/v1/txt2img
    img2imgUrl: http://127.0.0.1:7861/sdapi/v1/img2img

spring:
  application:
    name: stablediffusion
  datasource:
    url: jdbc:postgresql://localhost:5432/poketex
    username: postgres
    password: desene123
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api