server:
  port: 8089

api:
  base-url:
    poketex: http://localhost:8084
    image-to-image: http://localhost:8081
    chatgpt: http://localhost:8088

spring:
  application:
    name: breeding
  datasource:
    url: jdbc:postgresql://localhost:5432/poketex
    username: postgres
    password: desene123
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api